---
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v1.*"

jobs:
  test:
    runs-on: ubuntu-24.04
    container: golang:1.26.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Set up revive
        run: |
          curl -s -L https://github.com/mgechev/revive/releases/download/v1.14.0/revive_linux_amd64.tar.gz | tar xzf - -C $(go env GOROOT)/bin revive
      - name: Set up gosec
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOROOT)/bin v2.23.0
      - name: Check code modernization
        run: make modernize-check
      - name: Run tests
        run: make test

  goreleaser:
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Run checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.1
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
